export {
  HereticSocketClient,
  attachWorkspaceToDaemon,
  healthcheckDaemon,
  makeClientRequestId,
  queryMcpStatus,
  queryModelCatalog,
  queryReferenceBundle,
  querySessionSnapshot,
  queryTools,
  recoverTurnAnswerFromSnapshot,
  resolveHereticPaths,
  setRuntimeModel,
  setRuntimeProfile,
  setRuntimeProvider,
  setRuntimeStream,
  submitTurn,
  submitTurnAndWait,
} from '@saiso/heretic-saiso-protocol-client';
